site_name: Invoke-Tasks
site_author: 'Thomas Lehmann <tlehmann@posteo.de>'
site_url: 'https://thomas-lehmann-private.github.io/Invoke-Tasks/'
repo_url: 'https://github.com/thomas-lehmann-private/Invoke-Tasks'

nav:
  - Home: index.md
  - User Guide:
    - task-registration.md
    - analyse-task-registration.md
    - static-code-analysis.md
    - command-line-details.md
    - useful-links.md

theme:
  name: material

plugins:
  - search
  - mermaid2
  - autolinks

markdown_extensions:
  - mkdocs_graphviz
  - admonition
  - footnotes
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
