# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell
name: invoke-tasks-build-actions
on: [push]
jobs:
  run-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    name: Build on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2            # checks out of repository and download it to the runner
      - run: pwsh -file ./Invoke-Tasks.ps1

